csvmanager/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^upload$', views.upload, name='upload'),
    url(r'^document$', views.document, name='document'),
    url(r'^post_upload$', views.post_upload, name='post_upload'),
    url(r'', views.index, name='index')
]

keen/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('csvmanager.urls', namespace='csvmanager'))
]

csvmanager/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

csvmanager/views.py
import os
import json
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .validator import Validator


TEMP_FILE_NAME = 'csvmanager/static/files/temp.csv'
DATA_FILE_NAME = 'csvmanager/static/files/data.csv'


def index(request):
    ''' Default view '''
    return HttpResponseRedirect(reverse('csvmanager:upload'))


def upload(request):
    ''' Page for uploading cvs document '''
    return render(request, 'csvmanager/upload.html', {})


def document(request):
    ''' View document '''
    data = {}
    with open(DATA_FILE_NAME, 'rb') as fh_in:
        records = [x.split(',') for x in fh_in.read().split('\n') if x]
        data['header'] = records[0]
        data['records'] = records[1:]
    return render(request, 'csvmanager/document.html', data)


def post_upload(request):
    ''' Handle upload '''
    error = ''
    if request.method == 'POST' and request.FILES:
        fh_in = request.FILES.values()[0]
        if fh_in.size > 1024*1024:
            error = 'File too large'
        else:
            #data = fh_in.read()
            validator = Validator()
            with open(TEMP_FILE_NAME, 'wb+') as fh_out:
                for record in fh_in:
                    is_valid, msg = validator.is_valid(record)
                    if not is_valid:
                        error = msg
                        break
                    fh_out.write(record)

            if not error:
                ''' Successful download and validation, move temporary file '''
                os.rename(TEMP_FILE_NAME, DATA_FILE_NAME)
                
    if error:            
        return render(request, 'csvmanager/error.html', {'error': error})
    else:
        return HttpResponseRedirect(reverse('csvmanager:document'))

csvmanager/templates/csvmanager/base.html
<!doctype html>
<html ng-app="csvapp">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Csv Manager</title>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular-resource.min.js">
  </script>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular-route.min.js">
  </script>

  <link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" />

  <style>
    body {
      background-color: #DDD;
    }

    div.content-box {
      background-color: #FFF;
      border-radius: 8px;
      padding-bottom: 10px;
    }

    div.outer-content-box {
      margin-bottom: 15px;
    }

    div.content-box h2 {
      text-align: center;
    }
  </style>
  {% block html_head %}
  {% endblock %}
</head>

<body>
  <div class="container-fluid outer-content-box">
    <div class="row">
      <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 content-box">
        {% block html_body %}
        {% endblock %}
      </div>
    </div>
  </div>
</body>
</html>

csvmanager/templates/csvmanager/document.html
{% extends 'csvmanager/base.html' %}

{% block html_head %}

{% endblock %}


{% block html_body %}
  <h2>Data</h2>
  <table class="table table-striped">
    <tr>
      {% for col in header %}
      <th>{{ col }}</th>
      {% endfor %}
    </tr>
    {% for record in records %}
    <tr>
      {% for field in record %}
      <td>{{ field }}</td>
      {% endfor %}
    </tr>
    {% endfor %}
  </table>

  <a href="/">Back</a>
{% endblock %}

csvmanager/templates/csvmanager/error.html
{% extends 'csvmanager/base.html' %}

{% block html_body %}
  <h2>Error</h2>
  <p>{{ error }}</p>

  <a href="/">Return</a>
{% endblock  %}

csvmanager/templates/csvmanager/upload.html
{% extends 'csvmanager/base.html' %}

{% block html_body %}
  <h2>Upload File</h2>
  <form enctype="multipart/form-data" method="post"
      class="form-horizontal"
      action="{% url 'csvmanager:post_upload' %}"
  >
    {% csrf_token %}
    <div class="form-group">
      <label class="col-sm-3 control-label">Upload File</label>
      <div class="col-sm-8">
        <input type="file" name="file"> <br />
      </div>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

  <a href="{% url 'csvmanager:document' %}">View Document</a>
{% endblock %}